services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    depends_on:
      - db
    command: ["/app/init.sh"]

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles

volumes:
  postgres_data:
  static_volume:
