# Generated by Django 5.1.4 on 2024-12-12 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Lifeguard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('W', 'Rescue action in the water'), ('P', 'First aid provided'), ('A', 'Pool malfunction')], default='P', max_length=1)),
                ('lifeguard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.lifeguard')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_management.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.pool')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('O', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='O', max_length=1)),
                ('lifeguard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.lifeguard')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_management.shift')),
            ],
        ),
    ]
