# Generated by Django 5.1.4 on 2024-12-18 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeguard',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lifeguard',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must contain between 9 and 15 digits and can start with '+'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='pool',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must contain between 9 and 15 digits and can start with '+'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
